# Generated by Django 4.1.7 on 2023-03-30 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_cree_tabla_usuarios'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='usuario',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='usuario',
            name='apellido',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nombre',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
